/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWallRouteImport } from './routes/_authenticated/wall'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrayersRouteImport } from './routes/_authenticated/prayers'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMemorizeRouteImport } from './routes/_authenticated/memorize'
import { Route as AuthenticatedListenRouteImport } from './routes/_authenticated/listen'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedGitSyncRouteImport } from './routes/_authenticated/git-sync'
import { Route as AuthenticatedCompanionRouteImport } from './routes/_authenticated/companion'
import { Route as AuthenticatedBibleRouteImport } from './routes/_authenticated/bible'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as ApiPublicWidgetVerseOfTheDayRouteImport } from './routes/api/public/widget/verse-of-the-day'
import { Route as ApiPublicHooksRevenuecatRouteImport } from './routes/api/public/hooks/revenuecat'
import { Route as ApiPublicDemoAskRouteImport } from './routes/api/public/demo/ask'
import { Route as AuthenticatedGroupsGroupIdRequestsRequestIdRouteImport } from './routes/_authenticated/groups.$groupId.requests.$requestId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWallRoute = AuthenticatedWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayersRoute = AuthenticatedPrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemorizeRoute = AuthenticatedMemorizeRouteImport.update({
  id: '/memorize',
  path: '/memorize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListenRoute = AuthenticatedListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGitSyncRoute = AuthenticatedGitSyncRouteImport.update({
  id: '/git-sync',
  path: '/git-sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanionRoute = AuthenticatedCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibleRoute = AuthenticatedBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const ApiPublicWidgetVerseOfTheDayRoute =
  ApiPublicWidgetVerseOfTheDayRouteImport.update({
    id: '/api/public/widget/verse-of-the-day',
    path: '/api/public/widget/verse-of-the-day',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRevenuecatRoute =
  ApiPublicHooksRevenuecatRouteImport.update({
    id: '/api/public/hooks/revenuecat',
    path: '/api/public/hooks/revenuecat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDemoAskRoute = ApiPublicDemoAskRouteImport.update({
  id: '/api/public/demo/ask',
  path: '/api/public/demo/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGroupsGroupIdRequestsRequestIdRoute =
  AuthenticatedGroupsGroupIdRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bible': typeof AuthenticatedBibleRoute
  '/companion': typeof AuthenticatedCompanionRoute
  '/git-sync': typeof AuthenticatedGitSyncRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/listen': typeof AuthenticatedListenRoute
  '/memorize': typeof AuthenticatedMemorizeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/prayers': typeof AuthenticatedPrayersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/wall': typeof AuthenticatedWallRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/api/public/demo/ask': typeof ApiPublicDemoAskRoute
  '/api/public/hooks/revenuecat': typeof ApiPublicHooksRevenuecatRoute
  '/api/public/widget/verse-of-the-day': typeof ApiPublicWidgetVerseOfTheDayRoute
  '/groups/$groupId/requests/$requestId': typeof AuthenticatedGroupsGroupIdRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bible': typeof AuthenticatedBibleRoute
  '/companion': typeof AuthenticatedCompanionRoute
  '/git-sync': typeof AuthenticatedGitSyncRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/listen': typeof AuthenticatedListenRoute
  '/memorize': typeof AuthenticatedMemorizeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/prayers': typeof AuthenticatedPrayersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/wall': typeof AuthenticatedWallRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/api/public/demo/ask': typeof ApiPublicDemoAskRoute
  '/api/public/hooks/revenuecat': typeof ApiPublicHooksRevenuecatRoute
  '/api/public/widget/verse-of-the-day': typeof ApiPublicWidgetVerseOfTheDayRoute
  '/groups/$groupId/requests/$requestId': typeof AuthenticatedGroupsGroupIdRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bible': typeof AuthenticatedBibleRoute
  '/_authenticated/companion': typeof AuthenticatedCompanionRoute
  '/_authenticated/git-sync': typeof AuthenticatedGitSyncRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/listen': typeof AuthenticatedListenRoute
  '/_authenticated/memorize': typeof AuthenticatedMemorizeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/prayers': typeof AuthenticatedPrayersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/wall': typeof AuthenticatedWallRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/api/public/demo/ask': typeof ApiPublicDemoAskRoute
  '/api/public/hooks/revenuecat': typeof ApiPublicHooksRevenuecatRoute
  '/api/public/widget/verse-of-the-day': typeof ApiPublicWidgetVerseOfTheDayRoute
  '/_authenticated/groups/$groupId/requests/$requestId': typeof AuthenticatedGroupsGroupIdRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bible'
    | '/companion'
    | '/git-sync'
    | '/groups'
    | '/home'
    | '/listen'
    | '/memorize'
    | '/onboarding'
    | '/plans'
    | '/prayers'
    | '/profile'
    | '/reminders'
    | '/saved'
    | '/search'
    | '/settings'
    | '/study'
    | '/wall'
    | '/groups/$groupId'
    | '/api/public/demo/ask'
    | '/api/public/hooks/revenuecat'
    | '/api/public/widget/verse-of-the-day'
    | '/groups/$groupId/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bible'
    | '/companion'
    | '/git-sync'
    | '/groups'
    | '/home'
    | '/listen'
    | '/memorize'
    | '/onboarding'
    | '/plans'
    | '/prayers'
    | '/profile'
    | '/reminders'
    | '/saved'
    | '/search'
    | '/settings'
    | '/study'
    | '/wall'
    | '/groups/$groupId'
    | '/api/public/demo/ask'
    | '/api/public/hooks/revenuecat'
    | '/api/public/widget/verse-of-the-day'
    | '/groups/$groupId/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bible'
    | '/_authenticated/companion'
    | '/_authenticated/git-sync'
    | '/_authenticated/groups'
    | '/_authenticated/home'
    | '/_authenticated/listen'
    | '/_authenticated/memorize'
    | '/_authenticated/onboarding'
    | '/_authenticated/plans'
    | '/_authenticated/prayers'
    | '/_authenticated/profile'
    | '/_authenticated/reminders'
    | '/_authenticated/saved'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/study'
    | '/_authenticated/wall'
    | '/_authenticated/groups/$groupId'
    | '/api/public/demo/ask'
    | '/api/public/hooks/revenuecat'
    | '/api/public/widget/verse-of-the-day'
    | '/_authenticated/groups/$groupId/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDemoAskRoute: typeof ApiPublicDemoAskRoute
  ApiPublicHooksRevenuecatRoute: typeof ApiPublicHooksRevenuecatRoute
  ApiPublicWidgetVerseOfTheDayRoute: typeof ApiPublicWidgetVerseOfTheDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wall': {
      id: '/_authenticated/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof AuthenticatedWallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayers': {
      id: '/_authenticated/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof AuthenticatedPrayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memorize': {
      id: '/_authenticated/memorize'
      path: '/memorize'
      fullPath: '/memorize'
      preLoaderRoute: typeof AuthenticatedMemorizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listen': {
      id: '/_authenticated/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof AuthenticatedListenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/git-sync': {
      id: '/_authenticated/git-sync'
      path: '/git-sync'
      fullPath: '/git-sync'
      preLoaderRoute: typeof AuthenticatedGitSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companion': {
      id: '/_authenticated/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof AuthenticatedCompanionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bible': {
      id: '/_authenticated/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof AuthenticatedBibleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/api/public/widget/verse-of-the-day': {
      id: '/api/public/widget/verse-of-the-day'
      path: '/api/public/widget/verse-of-the-day'
      fullPath: '/api/public/widget/verse-of-the-day'
      preLoaderRoute: typeof ApiPublicWidgetVerseOfTheDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/revenuecat': {
      id: '/api/public/hooks/revenuecat'
      path: '/api/public/hooks/revenuecat'
      fullPath: '/api/public/hooks/revenuecat'
      preLoaderRoute: typeof ApiPublicHooksRevenuecatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo/ask': {
      id: '/api/public/demo/ask'
      path: '/api/public/demo/ask'
      fullPath: '/api/public/demo/ask'
      preLoaderRoute: typeof ApiPublicDemoAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/groups/$groupId/requests/$requestId': {
      id: '/_authenticated/groups/$groupId/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/groups/$groupId/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedGroupsGroupIdRoute
    }
  }
}

interface AuthenticatedGroupsGroupIdRouteChildren {
  AuthenticatedGroupsGroupIdRequestsRequestIdRoute: typeof AuthenticatedGroupsGroupIdRequestsRequestIdRoute
}

const AuthenticatedGroupsGroupIdRouteChildren: AuthenticatedGroupsGroupIdRouteChildren =
  {
    AuthenticatedGroupsGroupIdRequestsRequestIdRoute:
      AuthenticatedGroupsGroupIdRequestsRequestIdRoute,
  }

const AuthenticatedGroupsGroupIdRouteWithChildren =
  AuthenticatedGroupsGroupIdRoute._addFileChildren(
    AuthenticatedGroupsGroupIdRouteChildren,
  )

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRouteWithChildren
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRouteWithChildren,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibleRoute: typeof AuthenticatedBibleRoute
  AuthenticatedCompanionRoute: typeof AuthenticatedCompanionRoute
  AuthenticatedGitSyncRoute: typeof AuthenticatedGitSyncRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedListenRoute: typeof AuthenticatedListenRoute
  AuthenticatedMemorizeRoute: typeof AuthenticatedMemorizeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPrayersRoute: typeof AuthenticatedPrayersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedWallRoute: typeof AuthenticatedWallRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibleRoute: AuthenticatedBibleRoute,
  AuthenticatedCompanionRoute: AuthenticatedCompanionRoute,
  AuthenticatedGitSyncRoute: AuthenticatedGitSyncRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedListenRoute: AuthenticatedListenRoute,
  AuthenticatedMemorizeRoute: AuthenticatedMemorizeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPrayersRoute: AuthenticatedPrayersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedWallRoute: AuthenticatedWallRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDemoAskRoute: ApiPublicDemoAskRoute,
  ApiPublicHooksRevenuecatRoute: ApiPublicHooksRevenuecatRoute,
  ApiPublicWidgetVerseOfTheDayRoute: ApiPublicWidgetVerseOfTheDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
